### ISSUE TITLE
Unable to find my Server DNS

### ISSUE THREAD

**Issue by CupcakeLeaf** [jackcaver/PLGarage#1]
I opened my server and i did found my DNS, but, when i changed the DNS setting on my PS3, it did not work, because i could not even enter PSN, how do i get my server DNS and how do i connect it correctly?

**Comment by jackcaver** [comment]
The current server implementation does not provide a DNS server, so it has to be hosted by a different software.
If you're having troubles with setting up a DNS server please try searching on Google or contact a software delveloper, as i'm unable to provide a solution for this problem
