### ISSUE TITLE
Question, where can I obtain a "bombd" server to host an instance of this server? Is it included?

### ISSUE THREAD

**Issue by gvalue-04** [jackcaver/PLGarage#6]
Title explains

**Comment by jackcaver** [comment]
Bombd is not included with PLGarage, but you can use the one from derole1's MNR server

**Comment by gvalue-04** [comment]
How

**Comment by oryani618** [comment]
ok but like, how do you setup Bombd tho?

**Comment by jackcaver** [comment]
sorry, but PLGarage does not include a bombd, so you have to ask the author of the software you're using
